#!/usr/bin/env bash
# refresh-scan-focus.sh — regenerate the PR-daemon scan list (~/.config/prbot/repos.conf)
# as "the N most-recently-pushed repos across our orgs" PLUS any manually pinned repos.
#
# Why: watching whole orgs meant scanning hundreds of dormant repos every cycle. The daemon
# should focus on where work is actually happening — the top-N by GitHub pushedAt — while still
# letting you PIN specific repos that must always be watched regardless of recency.
#
#   refresh-scan-focus.sh                 # (default) recompute top-N + pinned → write repos.conf
#   refresh-scan-focus.sh refresh         # same as above
#   refresh-scan-focus.sh add o/r [o/r…]  # pin repo(s) (always watched), then recompute
#   refresh-scan-focus.sh rm  o/r [o/r…]  # unpin repo(s), then recompute
#   refresh-scan-focus.sh list            # show what repos.conf currently resolves to
#
# Config files under $CFG (auto-created with sane defaults on first run):
#   candidate-orgs.conf       orgs whose repos form the top-N candidate pool (one per line)
#   candidate-personal.conf   individual personal repos ALSO eligible for the top-N pool
#   focus-manual.conf         PINNED repos — always in repos.conf, on top of the N (the "追加" list)
#
# Env knobs:
#   FOCUS_TOP_N   how many recent repos to auto-include   (default 8)
#   PRBOT_CFG     config dir                              (default ~/.config/prbot)
set -uo pipefail

CFG="${PRBOT_CFG:-$HOME/.config/prbot}"
TOP_N="${FOCUS_TOP_N:-8}"
OUT="$CFG/repos.conf"
ORGS_F="$CFG/candidate-orgs.conf"
PERS_F="$CFG/candidate-personal.conf"
PIN_F="$CFG/focus-manual.conf"

mkdir -p "$CFG"
[ -f "$ORGS_F" ] || printf 'AAStarCommunity\niDoris-ai\nMushroomDAO\n' > "$ORGS_F"
[ -f "$PERS_F" ] || printf 'jhfnetboy/CMIC\njhfnetboy/goutou\njhfnetboy/PowerSalesMan\n' > "$PERS_F"
[ -f "$PIN_F" ]  || : > "$PIN_F"

# read a conf file: strip comments + blanks, trim, drop empties
readconf() { sed 's/#.*//' "$1" 2>/dev/null | awk 'NF{$1=$1;print $1}'; }

pin_add() {
  local r
  for r in "$@"; do
    case "$r" in */*) ;; *) echo "skip (not owner/repo): $r" >&2; continue ;; esac
    grep -qxF "$r" "$PIN_F" 2>/dev/null || echo "$r" >> "$PIN_F"
  done
}
pin_rm() {
  local r tmp; tmp="$(mktemp)"
  cp "$PIN_F" "$tmp"
  # NOTE: do NOT gate `mv` on grep's exit status. grep -v returns 1 when it emits
  # ZERO lines (i.e. removing the only pinned repo empties the file) — `&& mv` would
  # then skip the update and silently keep the repo. Always take grep's output.
  for r in "$@"; do grep -vxF "$r" "$tmp" > "$tmp.2" || true; mv "$tmp.2" "$tmp"; done
  mv "$tmp" "$PIN_F"
}

refresh() {
  local scan; scan="$(mktemp)"   # tab-separated: pushedAt \t owner/repo
  local org r ts

  # org repos (non-archived) → candidate pool
  while IFS= read -r org; do
    [ -z "$org" ] && continue
    gh repo list "$org" --no-archived --limit 300 --json nameWithOwner,pushedAt 2>/dev/null \
      | python3 -c "import json,sys
for x in json.load(sys.stdin): print(x['pushedAt']+'\t'+x['nameWithOwner'])" >> "$scan"
  done < <(readconf "$ORGS_F")

  # personal candidates → also eligible for the top-N
  while IFS= read -r r; do
    [ -z "$r" ] && continue
    ts="$(gh repo view "$r" --json pushedAt 2>/dev/null \
      | python3 -c "import json,sys;print(json.load(sys.stdin).get('pushedAt',''))" 2>/dev/null)"
    [ -n "$ts" ] && printf '%s\t%s\n' "$ts" "$r" >> "$scan"
  done < <(readconf "$PERS_F")

  # top-N by pushedAt desc
  local topn; topn="$(mktemp)"
  sort -r "$scan" | awk -F'\t' '!seen[$2]++{print $2}' | head -n "$TOP_N" > "$topn"

  # pinned repos (always included), minus any already in top-N
  local pins; pins="$(mktemp)"
  readconf "$PIN_F" | awk 'NF' | while IFS= read -r r; do
    grep -qxF "$r" "$topn" || echo "$r"
  done > "$pins"

  # emit repos.conf
  {
    echo "# GENERATED by refresh-scan-focus.sh — DO NOT hand-edit."
    echo "# Default scan scope = top-$TOP_N most-recently-pushed repos + pinned repos."
    echo "# 改候选池: candidate-orgs.conf / candidate-personal.conf"
    echo "# 加/减常驻: refresh-scan-focus.sh add|rm <owner/repo>  (写入 focus-manual.conf)"
    echo "# 重新计算:  refresh-scan-focus.sh   (repos 有新提交后跑一次，Top-$TOP_N 会变)"
    echo
    echo "# --- top-$TOP_N by recent push (auto) ---"
    cat "$topn"
    if [ -s "$pins" ]; then
      echo
      echo "# --- pinned / 手动追加 (focus-manual.conf, 恒扫) ---"
      cat "$pins"
    fi
  } > "$OUT"

  echo "wrote $OUT:"
  grep -vE '^\s*#|^\s*$' "$OUT" | nl -w2 -s'. '
  rm -f "$scan" "$topn" "$pins"
}

case "${1:-refresh}" in
  refresh) refresh ;;
  add) shift; [ $# -ge 1 ] || { echo "usage: add <owner/repo>..." >&2; exit 2; }; pin_add "$@"; refresh ;;
  rm)  shift; [ $# -ge 1 ] || { echo "usage: rm <owner/repo>..."  >&2; exit 2; }; pin_rm  "$@"; refresh ;;
  list) echo "repos.conf resolves to:"; grep -vE '^\s*#|^\s*$' "$OUT" | nl -w2 -s'. ' ;;
  *) echo "usage: refresh-scan-focus.sh [refresh|add <o/r>|rm <o/r>|list]" >&2; exit 2 ;;
esac
