#!/usr/bin/env python3
"""scan_scope.py — THE single source of truth for "which repos does the daemon scan".

Before this module there were three answers to that question and they disagreed:

  1. `ORGS = ["AAStarCommunity", "iDoris-ai", "MushroomDAO"]` hardcoded in FOUR
     scripts (poll_prs, poll_fix_queue, review_queue, start_loop_scope) — this was
     the list that actually ran.
  2. `.state/pr-daemon/start-loop-pinned.json` — read only by start_loop_scope, as
     pins layered on top of (1).
  3. `~/.config/prbot/repos.conf` (generated from `focus-manual.conf`) — read only
     by `review_watch.py`, which is not running. Adding a repo here changed nothing.

So "pin a repo" meant two different edits in two different files and still missed
the org list, and a repo could be in one, two, or three of them. Now there is one
file and every consumer reads it through here.

THE FILE: ~/.config/prbot/repos.conf
  - Generated by `refresh-scan-focus.sh` (top-N by recent push + pinned extras).
  - Hand-edits go in `~/.config/prbot/focus-manual.conf`, never in repos.conf
    itself — the generator overwrites it. `$pr add <repo>` does this for you.
  - Blank lines and `#` comments are ignored.

`orgs()` derives the org list FROM that file rather than carrying its own copy, so
adding `SomeOrg/repo` to the scan list automatically widens the org-wide GraphQL
sweep instead of silently doing nothing.
"""
from __future__ import annotations

import pathlib

CFG = pathlib.Path.home() / ".config" / "prbot"
CONF = CFG / "repos.conf"
ORGS_CONF = CFG / "candidate-orgs.conf"

# Only used if the config files are missing/empty — keeps a fresh checkout working
# rather than silently scanning nothing (which would look like "no PRs").
FALLBACK_ORGS = ["AAStarCommunity", "iDoris-ai", "MushroomDAO"]


def repos() -> list[str]:
    """Every `OWNER/REPO` in the scan list, in file order, de-duplicated."""
    try:
        raw = CONF.read_text(encoding="utf-8")
    except OSError:
        return []
    out: list[str] = []
    for line in raw.splitlines():
        line = line.split("#", 1)[0].strip()
        if "/" in line and line not in out:
            out.append(line)
    return out


def orgs() -> list[str]:
    """Owners whose repos are swept WHOLESALE, from `candidate-orgs.conf`.

    Deliberately NOT derived from repos.conf's owners: that file legitimately
    contains personal repos (`jhfnetboy/CMIC`, `jhfnetboy/NextStop`), and treating
    their owner as a sweep target would pull in the hundreds of personal repos the
    include-list exists to keep out.
    """
    try:
        raw = ORGS_CONF.read_text(encoding="utf-8")
    except OSError:
        return list(FALLBACK_ORGS)
    out: list[str] = []
    for line in raw.splitlines():
        line = line.split("#", 1)[0].strip()
        if line and "/" not in line and line not in out:
            out.append(line)
    return out or list(FALLBACK_ORGS)


def extra_repos() -> list[str]:
    """Listed repos that live OUTSIDE the swept orgs — each needs its own query."""
    o = orgs()
    return [r for r in repos() if r.split("/", 1)[0] not in o]


def is_in_scope(repo: str) -> bool:
    """Allowlist check (pr SKILL's ABSOLUTE CONSTRAINT #4).

    In scope iff listed explicitly, or owned by a swept org. A personal repo that
    is not listed is never in scope, however it was reached.
    """
    return repo in repos() or repo.split("/", 1)[0] in orgs()


if __name__ == "__main__":
    print(f"config     : {CONF}")
    print(f"swept orgs : {', '.join(orgs())}   (from {ORGS_CONF.name})")
    print(f"listed     : {len(repos())} repos")
    for r in repos():
        mark = "  " if r.split("/", 1)[0] in orgs() else "📌"
        print(f"  {mark} {r}")
    ex = extra_repos()
    if ex:
        print(f"outside swept orgs (queried individually): {', '.join(ex)}")
